### ISSUE TITLE
Error: Unsupported format

### ISSUE THREAD

**Issue by jamaluddinrumi** [ascorbic/get-pixels#16]
Hi Matt, 

Thank's for `@unpic/pixels@` amazing library.  I want to report error, but i don't know how to make a reproduction.

```
"@unpic/pixels": "^1.2.2",
```

```
Astro version            v2.10.15
Package manager          npm
Platform                 darwin
Architecture             arm64
Adapter                  Couldn't determine.
Integrations             astro-i18next, astro-imagetools, @storyblok/astro, @astrojs/tailwind, @astrojs/sitemap, astro-robots-txt, @astrojs/partytown, @vite-pwa/astro-integration, astro-compress, astro-critters
```

```
file:///Users/jamaluddinrumi/Public/www/indomascot.astro/node_modules/@unpic/pixels/esm/src/get-pixels.js:22
    throw new Error("Unsupported format");
          ^

Error: Unsupported format
    at decodeImageData (file:///Users/jamaluddinrumi/Public/www/indomascot.astro/node_modules/@unpic/pixels/esm/src/get-pixels.js:22:11)
    at getPixels (file:///Users/jamaluddinrumi/Public/www/indomascot.astro/node_modules/@unpic/pixels/esm/src/get-pixels.js:39:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async generatePlaceholders (file:///Users/jamaluddinrumi/Public/www/indomascot.astro/dist/chunks/pages/index.astro.1215b367.mjs:223:37)
    at async file:///Users/jamaluddinrumi/Public/www/indomascot.astro/dist/chunks/pages/index.astro.1215b367.mjs:228:148
    at async AstroComponentInstance.render (file:///Users/jamaluddinrumi/Public/www/indomascot.astro/dist/chunks/astro.5695ae87.mjs:972:7)
    at async Object.render (file:///Users/jamaluddinrumi/Public/www/indomascot.astro/dist/chunks/astro.5695ae87.mjs:1425:7)
    at async renderChild (file:///Users/jamaluddinrumi/Public/www/indomascot.astro/dist/chunks/astro.5695ae87.mjs:934:5)
    at async Object.renderToFinalDestination (file:///Users/jamaluddinrumi/Public/www/indomascot.astro/dist/chunks/astro.5695ae87.mjs:757:7)
    at async RenderTemplateResult.render (file:///Users/jamaluddinrumi/Public/www/indomascot.astro/dist/chunks/astro.5695ae87.mjs:1041:9)
    at async renderChild (file:///Users/jamaluddinrumi/Public/www/indomascot.astro/dist/chunks/astro.5695ae87.mjs:934:5)

Node.js v20.12.0
error: script "build" exited with code 1
```

**Comment by jamaluddinrumi** [comment]
apparently it's my mistake. 

i'm just turn out that there is a missing photo in my storyblok content.
